name: Deploy Flutter Web
on:
  push:
    branches: [ "main" ] # main에 올리면 자동 배포
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2 # 플러터 환경 설치
      
      - run: flutter build web --release \
          --base-href "/${{ github.event.repository.name }}/" --dart-define=API_URL=${{ secrets.ORG_API_URL }} # 빌드할 frontEnd_URL 및 API_URL Secret 추가
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3 # gh-pages 브랜치로 전송
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web